### ISSUE TITLE
Dark mode text contrast too high

### ISSUE THREAD

**Issue by Palivec** [Automattic/simplenote-android#1018]
Hi, the contrast between the white text and black background in the note view is very high and badly readable, like an old bootscreen, it almost hurts the eyes, especially the larger paragraphs. It would be nice to dim the text a little, in a modern way, use light gray instead of pure white.

**Comment by theck13** [comment]
That is not a bug.  The contrast of **_Dark_** is intentional to meet accessibility standards so that it is visible to everyone including those with vision impairment.  If you prefer a previous version of the app with a different color scheme, you can download and install it from the [releases](https://github.com/Automattic/simplenote-android/releases) page.
