### ISSUE TITLE
Suggestion - Add select/unselect all notes option

### ISSUE THREAD

**Issue by stavares843** [Automattic/simplenote-android#1048]
### What
When going to all notes, if user wants to select multiple notes user needs to select one by one. Would be good to have a select/unselect all notes.

### Why
I think would be great to select/unselect all notes at once.

### How

When selecting a note, maybe we could add a select/unselect all icon to select/unselect all notes at once.

![Screenshot_1590766167](https://user-images.githubusercontent.com/29093946/83340382-1c99e880-a2cf-11ea-9f8a-4529c3f486b0.png)

**Comment by theck13** [comment]
I tried adding a **_Select All_** action to multi-select mode a while back.  There were no problems with the interface, but the backend (i.e. Simperium) had issues with **_Toggle Pin to Top_** and **_Trash_** actions for all selected notes.  Since it was a spike and a nice-to-have feature, it was dropped.

Tapping the back arrow in the app bar is the same as unselecting all.

I'll close this issue for now since it's not one of our planned features at the moment and we won't be adding it soon.
