### ISSUE TITLE
Suggestion - Use in-app browser overall on the app

### ISSUE THREAD

**Issue by stavares843** [Automattic/simplenote-android#1049]
### What
When user taps on ''Login with WordPress'' it opens the in-app browser.
When the user taps on ''Terms and Conditions'' will open the browser the user uses on the device.

### Why
Maybe we could use the in-app browser overall on the app to avoid the user to exit the app.

### How
Using the in-app browser already used on when tapping on ''Login with WordPress'' could be used overall on the app.

![Screen Recording 2020-05-30 at 11 55 58 PM](https://user-images.githubusercontent.com/29093946/83340553-a0ed6b00-a2d1-11ea-8275-00116978907b.gif)

**Comment by theck13** [comment]
The **_Log In with WordPress.com_** feature uses the [AppAuth-Android](https://github.com/openid/AppAuth-Android/tree/a7730439c0a8ac0485d59ea894a9bf04e8578d14) library, which uses [Chrome Custom Tabs in the `AuthorizationService` class](https://github.com/openid/AppAuth-Android/blob/a7730439c0a8ac0485d59ea894a9bf04e8578d14/library/java/net/openid/appauth/AuthorizationService.java#L30).  That's why is appears to be an in-app browser.  However, the app doesn't actually import the [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs) library.  If we did, it would increase our app size and potential be a point of failure.  For those reasons, we prefer to use the device's default browser outside of the authentication module.  Since the current implementation is the perferred behavior, I'll close this issue.
