### ISSUE TITLE
Missing Collaborate option

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-android#1156]
### Expected

I expect to see the Collaborate option when I tap on the Info panel on when I'm viewing a note as mentioned in the [Help document](https://simplenote.com/help/#sharing).

### Observed

The Collaborate option isn't found after tapping Info icon when viewing a note.

### Reproduced

1. Go to a note on the Simplenote app
2. Tap on the Info icon
3. See that the Collaborate option is missing

### Screenshot

![Screenshot_2020-09-22-14-29-59-39_dd6b2219cb0a90b8a293feeeaec0487a](https://user-images.githubusercontent.com/40906847/93850475-c79c3b00-fce0-11ea-9801-089ada2e4f8f.jpg)

Device Make: OPPO
Device Model: Reno 4
Android Version: 10.0.0
Simplenote Version: 2.11-rc-1 (116)

**Comment by theck13** [comment]
Android was mistakenly listed on the Help page as one of the apps with collaboration in the ***Information*** sheet.  Collaboration was never included in the ***Information*** sheet like iOS.  It was always accessed using the tag field as mentioned in the same frequently asked question quoted below.

> If you’d like others to view and edit one of your notes, add their email address as a tag.

We're planning to update collaboration across all platforms soon.  I'll close this issue since it was a mistake on the Help screen and we won't be adding collaboration to the ***Information*** sheet in the updates.  I've updated [that question on the Help page](https://simplenote.com/help/#sharing) as well.
