### ISSUE TITLE
Collaboration emails containing periods can't be added with Swiftkey keyboard

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-android#1158]
### Expected

I would expect to be able to add an email with a period (.) in it as a collaborator from the tag section.
### Observed

If you use the Microsoft Swiftkey keyboard when the period is added the text turns to a tag right away and the email can't be added.
### Reproduced

1. Install the Microsoft Switkey keyboard on your device and activate it.
2. Go to Simplenote and open a note to add a new collaborator using an email with a period in it. For example, `abc.abc@mail.com`
3. See the tag get added as soon as you enter the dot (.).

![Screen Recording 2020-09-23 at 01 14 42 pm](https://user-images.githubusercontent.com/10325627/94011143-d8ab8180-fd9e-11ea-8eff-575eb634d4e0.gif)

Device Make: User device in video is different than mine, I reproduced in Samsung
Device Model: Tab A
Android Version: 10.0.0
Simplenote Version: 2.10-rc-2(114)
Reported by user in 3336469-zen

**Comment by theck13** [comment]
The Microsoft Swiftkey keyboard automatically adds a space after punctuation.  The Simplenote **_Add tag..._** field submits a tag name when a space is entered since spaces are not allowed in tag names.  Therefore, using the Microsoft Swiftkey keyboard will submit a tag when a space is automatically added after a period is entered.

There are a few workarounds.  First, paste the email address with a period into the **_Add tag..._** field.  Then, tap the **_Space_** or **_Enter_**/**_Return_** key to submit the tag.  Second, don't use Microsoft Swiftkey when entering a tag for a note.  Third, disable **_Smart punctuation spacing_** in the Microsoft Swiftkey keyboard settings.  Note that disabling the **_Smart punctuation spacing_** only affects the physical hardware keyboard and not the virtual software keyboard while using Microsoft Swiftkey.  See the steps and screenshots below to disable the setting.

1. Tap the ellipsis icon in the Microsoft Swiftkey keyboard.
2. Tap the **_Settings_** button in the Microsoft Swiftkey keyboard.
3. Tap the **_Typing_** item in the **_Microsoft Swiftkey_** settings.
4. Tap the **_Physical keyboard_** item in the **_Typing_** settings.
5. Tap the **_Smart punctuation spacing_** item in the **_Physical keyboard_**  settings.

![microsoft_swiftkey_settings](https://user-images.githubusercontent.com/3827611/94025834-2f509580-fd76-11ea-8545-d1cd3e5728e3.png)

The option to [turn off automatically adding spaces after punctuation has been a highly-requested feature for the Microsoft Softkey keyboard for years](https://support.swiftkey.com/hc/en-us/community/posts/115000392469--Feature-Request-Turn-off-auto-spaces).  In the case of Simplenote, it directly conflicts with tag submission.  Since there are workarounds and the behavior is specific to the Microsoft Swiftkey keyboard, I'm going to close this issue as `wontfix`.
