### ISSUE TITLE
Search in Japanese is not accurate 

### ISSUE THREAD

**Issue by rossanafmenezes** [Automattic/simplenote-android#1191]
3452787-zen

Using Simplenote on Windows 10, web app and Android adding notes in Japanese. User reported that when they do a search on the Android App the delimiter processing of the hit item is completely incorrect while it works fine on Windows and in the Web app doing the exact same search. 

Also, the number of hits does not match when you do a search on Android and Win/Web app. 

### Expected

When you search for a word in English for example, only the word is highlighted on each note like this:

![Annotation on 2020-11-03 at 07-31-33](https://user-images.githubusercontent.com/30724184/97985725-a9792e80-1da6-11eb-84f5-e9d07157ff38.png)

### Observed

In Japanese, the highlighted result is not limited to the searched item

![Annotation on 2020-11-03 at 07-36-59](https://user-images.githubusercontent.com/30724184/97986247-6ff4f300-1da7-11eb-9907-687a386be86f.png)

There are more screenshots in the ticket if needed. 

### Reproduced

1. Go to Simplenote Android app and add a text in Japanese
2. Tap on the search icon and search for part of the text
3. Note that the highlighted item(s) are not restricted to the searched term. 

Note:

I was able to reproduce this on a Pixel 2 using Android 11 and SN version 2.11.1 (121). However, the Pixelbook (13421.73.0 (Official Build) stable-channel eve) version, the search worked fine ( Chrome OS Version 86.0.4240.112 (Official Build) (64-bit).

Device Make: Google
Device Model: Pixel 2
Android Version: 11.0.0
Simplenote Version: 2.11.1 (121)

The user's info:

Device Make: Samsung
Device Model: Samsung Galaxy note10 + SCV45
Android Version: 10 
Simplenote Version: 2.11.1 (121)

And 

 HUAWEI MediaPad M3 Lite CPN-W09
Android 7
Simplenote Version: 2.11.1 (121)

**Comment by theck13** [comment]
This is expected behavior.  Simplenote Android matches the full word from the beginning character of the word and highlights the whole word.  This happens with languages other than Japanese including English.  As an example, searching for "simple" highlights "Simplenote" in the search results.  See the screenshot below for illustration.

<kbd><a href="https://user-images.githubusercontent.com/3827611/97997442-2f48aa00-1da6-11eb-9462-2b5291f669e6.png"><img src="https://user-images.githubusercontent.com/3827611/97997442-2f48aa00-1da6-11eb-9462-2b5291f669e6.png" width="300"></a></kbd>

Searching within words is more apparent in languages like Japanese where words aren't always delimited by spaces.  That issue for Japanese specifically is described in https://github.com/Automattic/simplenote-android/issues/594.

I created an issue, https://github.com/Automattic/Simplenote-United/issues/69, to use the same search method across platforms.
