### ISSUE TITLE
Cursor jumps to the beginning of the first line (header) and feels sluggish on older tablet

### ISSUE THREAD

**Issue by mzorz** [Automattic/simplenote-android#1231]
### Expected
Cursor should not jump unexpectedly, but rather stay at the position where text is being entered.

### Observed
A user reported on Zendesk:
> In the midst of typing, cursor snaps back to the beginning of the first line (header). Not every time, not every note. To try to fix, I shut down the app and start again, which sometimes works.

> As for a screenshot, it is a dynamic bug, so all you will see is the
cursor appearing at the first position of the first line, where it will
have moved spontaneously from the current typing location.

> As you can see, it is an older tablet, my comfortable old favorite. I
have newer ones more powerful and running Android 9 or 10. My
observation is that in addition to this bug, Simplenote on this older
tablet is relatively sluggish, compared to its performance on those
newer tabs. I am suspecting this may be a source of the problem.

### Reproduced
Couldn't replicate, but this is the information the user reported:

Samsung Galaxy A (SM-T350)
Android 7.1.1
Simplenote 2.1 (125)

**Comment by theck13** [comment]
Thanks for the report.

> Simplenote on this older tablet is relatively sluggish, compared to its performance on those newer tabs.

It sounds like their issue is specific to their older device, which is 5-6 years old, and/or their Android version, which is 4 years old.  If they're not having issues with their newer devices, then the issue with their older device is probably due to the older device.  Because of that, I'm going to close this issue as `wontfix`.
