### ISSUE TITLE
Add the option to match search based on content of word, not first letters.

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-android#1250]
### What

User would like the option to search for any letters of the word on Android similar to how they can on the web app and Windows Electron. For example, You can find "Aretha" if you type "aret" in the search box but you can't find "Aretha" if you type "retha". 

### Why

This isn't an issue in the web app or electron and can be handy to look up notes without knowing having to type in the exact characters. This user seems to use the app to for a lexicon and with different languages, so I think it's easier to find full words you may be learning without needing to know the exact spelling.

### How

Screenshots available in the ticket of how this works on the web app.

I'm adding this here as I'm not sure if it's a bug or a feature difference. 

3595197-zen
Asking the user for device confirmation.

**Comment by theck13** [comment]
This is expected behavior.  Simplenote Android matches the full word from the beginning character of the word.  That's a limitation of full-text search, which Android uses and the other platforms do not.

I created an issue, https://github.com/Automattic/Simplenote-United/issues/69, to use the same search method across platforms.  I'll close this issue as a duplicate.
