### ISSUE TITLE
Typing [/ exposes a list of some notes, when clicked they paste the note and some code

### ISSUE THREAD

**Issue by zdenys** [Automattic/simplenote-android#1334]
### Observed

In a new or existing note type `[` followed by `/` and see a list of some notes popping up. When you tap any of them, it pastes the note and some additional code of the type `[NOTE CONTENT](simplenote://note/aa4ff248b00f4feea45d1059c8722fba)`
### Expected

See no list of notes pop up, unless it's a feature?
### Reproduced

1. In a new or existing note type `[` square bracket followed by `/` slash and see a list of some notes popping up.
2. When you tap any of them, it pastes the note and some additional code of the type `[NOTE CONTENT](simplenote://note/aa4ff248b00f4feea45d1059c8722fba)`

https://user-images.githubusercontent.com/39308239/109392936-b5759700-7927-11eb-9689-c9d416fa5436.mp4

### Device

Device Make: Xiaomi  
Device Model: Mi A1  
Android Version: 9  
Simplenote Version: 2.15 (130)

#dogfood #manualtesting

**Comment by pachlava** [comment]
@zdenys thanks for the notice! This is actually a feature which allows quick insertion of internal links - a link to another note of yours. This comes handy in markdown preview. To start using it, the user needs to type '[' and any character - note names with this character will be shown for selection. In your case, this character was '/' - and all notes with this character in name were shown.

**Comment by zdenys** [comment]
Oh wow! That's a TIL for me. Is this feature documented somewhere? I could not find it here https://simplenote.com/help/ So without knowing it's a feature it may be confusing, so I think it should be documented. 

By the way, my note was not in Markdown format (although I use it in some notes indeed), so it was even more confusing. Think of a user who is not aware of Markdown at all. I hope this can be documented so users can read an explanation about this feature. Thank you, @pachlava!

**Comment by pachlava** [comment]
@zdenys You are right, there's no direct mention of internal link autocomplete in help, but there's a link to [this page](https://simplenote.com/2020/11/03/introducing-internal-links/) which is available from the [help page](https://simplenote.com/help/#internal-links). I think it's described on a different page because of the size.

Internal links autocomplete work regardless of Markdown being active or not, since it's not a Markdown-dependant feature, however, it uses the Markdown link formatting. The only difference is that the link will be displayed nicely in MD preview, if it's enabled. 🙂
