### ISSUE TITLE
Phrase search does not work properly 

### ISSUE THREAD

**Issue by LiwiuszPleandro** [Automattic/simplenote-android#1375]
Phrase search does not work properly. It worked fine in previous versions.

Expected: 
After searching for a phrase, it should show a list of notes in which it was found and then go to the specific field found

Observed: 
It does not go to a specific searched field in the note

Reproduced:
1.  Go to: magnifier, type ex. (number phone) +4887345643 and click search
2.  Correctly finds a notes in which the phrase appears +4887345643
3.  Error: Shows a random note in which the searched phrase is missing at all. Does not go to the searched field

- System Make: Phone Xiaomi 
- System Model: Note 5
- OS: Android 9 . Snapdragon 636
- OS version: MIUI 11.2 eu
- Simplenote app version (google play): 2.18 (138)

**Comment by pachlava** [comment]
@LiwiuszPleandro thank you for the report!

I just tried reproducing this with Samsung A31, Android 10, Simplenote 2.18 (138) and could not do this. Apart from different Android version, are there any specifics you can think of: note content, notes number, the number of times the phrase we search for is used in notes? Any additional information would be helpful.

Here is a video - could you please tell is steps are correct? (Screen with version number is not captured unfortunately due to security reasons):

https://user-images.githubusercontent.com/73365754/114911989-2addee00-9e28-11eb-9169-e3f999db3623.mp4

^ When typing in the values for search and hitting the magnifier button, the results are the same. In the video I'm tapping the search queries from history to save the time.

**Comment by pachlava** [comment]
Also, does the issue you describe looks anything similar to [this one](https://github.com/Automattic/simplenote-android/issues/1338)?

**Comment by LiwiuszPleandro** [comment]
@pachlava: yes, the error looks the same as this example: https://github.com/Automattic/simplenote-android/issues/1338 
In previous versions simplenoteapp worked fine. There has not been a newer android version on my phone for two years. I am updating every version of simplenoteapp. 

**The error occurs if the notes are large, one note is approx. 40-60,000 characters. Searches correctly in short notes.**

**Comment by pachlava** [comment]
Thank you @LiwiuszPleandro ! I have just added your report to initial #1338 and closing this one, to avoid accumulating duplicated issues.

**Comment by reginabally** [comment]
Another report in4003115-zd-woothemes:

>  When there is only one 'hit' within a note, the part of the note that gets displayed on the screen does not contain the hit. So I must hunt around the note to find the hit.
If I had to make a bet (because this is a common source of such bugs), I would guess that the bug doesn't appear when minimum font size is used as is typical of young developers.
