### ISSUE TITLE
Local mode

### ISSUE THREAD

**Issue by Donkey-Doug** [Automattic/simplenote-android#1405]
### What
Make it possible to use the app locally without having to create an account first. Make usage of an account optional for people that like syncing between devices or backups, but do not force creation of an account upon users that want a simple, local note taking app.

### Why
Privacy & safety - A local mode is more private.

**Comment by codebykat** [comment]
Hi @Donkey-Doug, thanks for getting in touch. One of the key features of Simplenote is continuous sync of user content across all devices where Simplenote is installed. Having an account is necessary for this, so, the business logic of the app requires an account. Using Simplenote without an account isn't something we plan to support, due to the risk of data loss from losing or wiping the data on a device. There are many other note-taking apps out there that do support an account-less mode.

As far as privacy and safety goes, you can learn more about our policies here: https://simplenote.com/help/#encryption

Note that while we take every precaution with your data, we do not recommend using Simplenote to store extremely sensitive information, such as passwords. Again, there are much better, specialized apps out there that are designed for the purpose (1Password, LastPass, etc.) and those are better-suited for that use case than a note-taking app (any note-taking app!).
