### ISSUE TITLE
Permanent delete option

### ISSUE THREAD

**Issue by Marco-Sulla** [Automattic/simplenote-android#1420]
Could you add an option, when you send a document to the trash, to remove instead permanently, directly?

**Comment by pachlava** [comment]
Thank you for opening a feature request @Marco-Sulla! I've just added your proposal to our internal feature requests tracker (we already have one similar request there). The tracker gives our developers the understanding of the most requested features, when it comes to adding new functionality. Closing your report here because of this, _thanks_!
