### ISSUE TITLE
Synchronization halted

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#1548]
### Observed
New or changed notes are not synched.

### Reproduced
Using two different Android Mobile Phones with mobile data and/or WLAN connection

1. Samsung A51: 
- I **_created_** a note yesterday (12.07.2022),
- changed it today (13.07.2022)
- it is not synched today (13.07.2022):

![Screenshot_20220713-185147_Simplenote](https://user-images.githubusercontent.com/22197180/178811244-8314887a-3a30-4fed-9896-56d0d3cd2bbc.jpg)

2. Samsung S21: 
- I **_change_** a note today (13.07.2022),
- it is not synched today (13.07.2022) ---> Synchronization data is not shown, and comparing with https://simplenote.com the note is not changed:

![Screenshot_20220713-185213_Simplenote](https://user-images.githubusercontent.com/22197180/178809994-02126c5d-9eee-439c-af23-9638bf139c2b.jpg)

### Software
Android Version: 12 
Simplenote Version: 2.23 (148)

**Comment by rezzap** [comment]
Hi there!

Thank you for letting us know about this issue and for taking the time to report it. Our team has been looking into this and is working on releasing an update that will fix the issue to allow you to access your notes from your Android app again.

In the meantime, you can log in to Simplenote from any web browser on Android by navigating to https://app.simplenote.com.

This will be fixed in the next release. 

Thank you!
