### ISSUE TITLE
Markdown preview: links are not "linkified"

### ISSUE THREAD

**Issue by maxme** [Automattic/simplenote-android#361]
Not sure if it's a theme problem or a conversion problem but links aren't styled in the Markdown preview:

![screenshot_20160524-105600](https://cloud.githubusercontent.com/assets/40213/15498205/ecc33aae-219e-11e6-9c72-3b2114796d60.png)

While they are in the edit mode:

![screenshot_20160524-105601](https://cloud.githubusercontent.com/assets/40213/15498213/fa0fbae8-219e-11e6-95a5-27ffbd7055e1.png)

**Comment by danielms215** [comment]
I'm confused. You aren't formatting the links with Markdown, so they are processed as plain text. If you wanted them to be linkified, you would write [http://simplenote.com](http://simplenote.com).

I don't think this is a bug.

**Comment by Ethsaam** [comment]
@danielms215 No that is not the case. While formatting with Markdown (Edit Mode), the app linkifies the text [http://simplenote.com](http://simplenote.com). But when you preview the text, where it is supposed to show all the processed Markdown text, somehow the url is not processed and displayed as normal text where as all other text formatting is correctly applied. 

I think it is a bug.

**Comment by Ethsaam** [comment]
@maxme I think this is deliberate, and may not be classified as a bug. If you have a look at Markdown's url syntax https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet then it might be more clear. Actually we need to specify the urls as follows:

`[Link Text to Display](url-link)`

So if you change the text to `[Simple Note](http://simplenote.com)` then you will get the correct preview of a URL.

I believe it's simply a question of feature, whether Markdown preview must automatically detect URLs. Simplenote automatically detects URLs in the Edit Mode `NotesActivity.java` so that is why we get the blue highlighted text in the edit mode. It's not being processed by some Mark Down processor in the Edit Mode.

**Comment by danielms215** [comment]
Ethsaam explained it pretty well. I believe we should close this.

**Comment by maxme** [comment]
Yes, you're right, I thought it was a part of the Markdown specs to automatically create links around URLs, but it's not if you look at: https://daringfireball.net/projects/markdown/syntax#misc

> Automatic Links

> Markdown supports a shortcut style for creating “automatic” links for URLs and email addresses: simply surround the URL or email address with angle brackets. What this means is that if you want to show the actual text of a URL or email address, and also have it be a clickable link, you can do this:

>     <http://example.com/>

> Markdown will turn this into:

>     <a href="http://example.com/">http://example.com/</a>
