### ISSUE TITLE
Design / authentication error with PIN usage in Simplenote Android application

### ISSUE THREAD

**Issue by lccunha** [Automattic/simplenote-android#409]
Hi team

I noticed a design and authentication error (a wrong credential request) in the use of the Simplenote Android application lock PIN

POC

1 access the android app of Simplenote > enable lock PIN
2 in the same 'settings' area click 'Exit'

You are prompted for a new login. Right

3 minimize the application
4 access the application again

The access PIN is requested even after the user exits the account. That seems wrong to me. When the user exits the PIN should be automatically deactivated.

In this scenario even leaving the account the user has to enter the PIN. If you have forgotten this credential you will be forced to remove and reinstall the application. This causes some inconvenience in relation to the use of the app.

Please check it.

**Comment by theck13** [comment]
Thanks for pointing this out.  I agree; forgetting the PIN would be frustrating.  You don't necessarily need to uninstall then reinstall the app though.  You can clear the app data within Android's Settings app (i.e. Settings > Apps > Simplenote > Storage > Clear Data on Android 7.1) to get around the scenario you mentioned.  However, that will delete any local notes which haven't been synced.  You can see what has been synced by checking the web app at https://app.simplenote.com/.

One thing to remember is that you can save notes locally on the device without being logged in.  In that case, you may still want to use the PIN lock.  For that reason, I'll close this issue since the app is working as expected.

Thank you for your interest in Simplenote!
