### ISSUE TITLE
Hitting Enter Indents a Note- Android 

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-android#679]
Using the Android app on a Pixelbook, when you hit enter to create a new line in a note, the text indents as if you hit tab. 

### Expected
Note to start on a new line and not indent. 

### Observed
According to user, the text indents instead. 

### Reproduced
I don't have a Pixelbook to try to reproduce this one

Make|Model|OS Version|App Version
-|-|-|-
Pixelbook|unsure|Android|1.7.0

Ticket: #2039468-zen

**Comment by theck13** [comment]
This is a [bug in Chrome OS](https://bugs.chromium.org/p/chromium/issues/detail?id=1021729) affecting all Android apps with multiline input fields (i.e. `EditText`).  It was fixed in Chrome OS 80, which is scheduled to be released today.  Pressing the **_Enter_** key will work as expected in Simplenote Android once the device is updated to Chrome OS 80.
