### ISSUE TITLE
Tags header is clickable and clicking on it opens the list of notes for the first tag item

### ISSUE THREAD

**Issue by anitaa1990** [Automattic/simplenote-android#726]
### Expected
The tag header should not be clickable.

### Observed
Th tag header is clickable. 

### Reproduced:
- Open the navigation drawer.
- Click on the Tag header.
- Notice that it opens the notes list corresponding to the first tag.

### Screenshots
<img width="300" src="https://user-images.githubusercontent.com/22608780/60569139-357ede80-9d8c-11e9-9207-08fe123c4a5f.gif">

**Comment by iskandergaba** [comment]
Investigating the problem.

**Comment by theck13** [comment]
@iskandergaba, this is related to https://github.com/Automattic/simplenote-android/pull/723 and https://github.com/Automattic/simplenote-android/issues/708.  The [`nav_drawer_row`](https://github.com/Automattic/simplenote-android/blob/056eda30016cca320a5250d1dbab1816ca1fe761/Simplenote/src/main/res/layout/nav_drawer_row.xml) layout contains the header and tag views, which is why the header open the first tag.

Don't spend too much time on this.  We've started discussions about updating the navigation drawer to eliminate bugs like this.

**Comment by iskandergaba** [comment]
@theck13 Alright. Thank you for the heads up.

**Comment by theck13** [comment]
This issue was resolved when we updated the navigation drawer in https://github.com/Automattic/simplenote-android/pull/814.
