### ISSUE TITLE
Passwords with Spaces Returns Error

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-android#896]
### Expected
When using a password with spaces it should be accepted on both the electron, iOS and Android app.

### Observed
When an account password includes a space the account can't log in on the Android app. An error is returned. 

### Reproduced
1. Go to your account settings and change your password to include a space, like "My password"
2. Sign out of your account on Android
3. Attempt to sign back in with the new account
4. See the error

![](https://cld.wthms.co/QrPeVP+)
(Image link: https://cld.wthms.co/QrPeVP )

Make|Model|Android Version|App Version
Pixel | 3 |10 | 2.2

Reported #2512866-zen

**Comment by dmsnell** [comment]
Just dropping by to note the possibility of sending unencoded passwords where a space should be `%20` but is incorrectly sent as literally a space.

**Comment by EdNoepel** [comment]
Still an issue:
Make|Model|Android Version|App Version
LG | G7 ThinQ | 9 | 2.5.1

**Comment by theck13** [comment]
This issue was fixed and will be included in the next release.  It's available in the current beta version, Simplenote 2.6-rc-1.  You can join the Android beta program to get this fix and other changes as soon as we develop them.  If that sounds like something you want, you can join at [https://play.google.com/apps/testing/com.automattic.simplenote](https://play.google.com/apps/testing/com.automattic.simplenote).  If you want to get the updated version of the app without joining the beta program, you can download and install it manually on your phone at [https://github.com/Automattic/simplenote-android/releases/tag/2.6-rc-1](https://github.com/Automattic/simplenote-android/releases/tag/2.6-rc-1).

**Comment by phowe** [comment]
I've installed 2.6-rc-1 on Android from the link above, but the same issue is occurring. (Having changed my password using the web app to include a space, I cannot login via the app; I get "Passwords must be a minimum of 4 characters excluding new lines, spaces and tabs". And how come this RC is not live yet?

**Comment by theck13** [comment]
It is live.  [Simplenote Android 2.6.0 was released May 31, 2020](https://github.com/Automattic/simplenote-android/releases/tag/2.6).  A bug was fixed with passwords containing spaces in https://github.com/Automattic/simplenote-android/pull/1233, which will be included in Simplenote Android 2.15.0.  Watch the [releases page](https://github.com/Automattic/simplenote-android/releases) to be notified when we release that version.
