### ISSUE TITLE
Add hint text to navigation drawer

### ISSUE THREAD

**Issue by SylvesterWilmott** [Automattic/simplenote-android#913]
Currently, when no tags exist, the tags section is hidden in the navigation drawer. Let's add some hint text in place of it to indicate that tags will appear there.

<img width="393" alt="Screenshot 2019-12-17 at 16 55 55" src="https://user-images.githubusercontent.com/36532468/71017165-1a135000-20ee-11ea-8689-31d88d788a27.png">

**Comment by BitsInMyBlood** [comment]
You want the hint text to be exactly what you've shown in the image, above?

**Comment by BitsInMyBlood** [comment]
I have this enhancement done, though I am only using a single line of text. Is that ok?
![image](https://user-images.githubusercontent.com/5923690/71707477-f8c58b80-2d9e-11ea-8959-a1e8afcfbb9c.png)

**Comment by BitsInMyBlood** [comment]
![image](https://user-images.githubusercontent.com/5923690/71707520-2dd1de00-2d9f-11ea-965a-14a23cd0e2fd.png)

**Comment by theck13** [comment]
We can't guarantee the text will always be limited to only one line with language translations.

**Comment by BitsInMyBlood** [comment]
I'm not sure how to make the overflow go to the next line. If you have a link you can share for a method to do this, I would appreciate it. Otherwise, I'm continuing to try..

**Comment by BitsInMyBlood** [comment]
Is it proper to wait to submit a pull request until this enhancement is perfect? Would adding a functionally correct solution to the request be Ok? Should I make the hint shorter, such as "No tags found."  or "Once used, tags display here."

**Comment by theck13** [comment]
It's best not to submit a pull request with bugs.  In the proposed solution, we _could_ have bugs due to language translations even if we use a very short phrase in English since we cannot guarantee the length of the text in another language _and_ the width of the navigation drawer could change based on the device screen size and density.

**Comment by BitsInMyBlood** [comment]
Yes I agree that it would be correct to not introduce the possibility for a bug. I'm using a new xml layout and textView for this, instead. Still not wrapping to the next line. Still looking for a solution. Any idea on making a navigationView item multi-line? Forgive my ignorance!

**Comment by theck13** [comment]
I don't think the standard `NavigationView` allows you to add a menu item statically through XML or programmatically through Java that is more than one line.  We want to keep using the standard `NavigationView` though.  We deliberately changed from a custom `NavigationView` layout to the standard implementation to avoid layout bugs like those with devices displaying a non-standard status bar height.

A possible solution would be to use the menu item's action view like the ***EDIT*** button in the ***Tags*** header.  Unfortunately, the action view is always end-aligned and will not align vertically with the menu items above it as shown in the design mockup if the text does not take up the full width of the navigation drawer.  Similar to the issue with the one-line-only solution, we can't guarantee the length of the text so that could be a potential bug with some languages and devices.

Those are my initial thoughts with this issue.  Let me know if you have any questions.

**Comment by BitsInMyBlood** [comment]
This issue of navigation drawer's sizing, alignment and/or dimensions seems to have plagued other designers for a while, now. A promising solution I found is to use a custom theme for the NavigationView element with the following:

<item name="android:lines">2</item>
<item name="android:ellipsize">end</item>

Unfortunately, this approach doesn't work. Either something changed since it was a valid solution or maybe I've done it wrong. Another solution is to override design_navigation_menu_item.xml from the Android Support Design Library. Is this something that has already been attempted?

**Comment by theck13** [comment]
I'm don't think anyone is working on this issue so I don't believe it has been attempted.

Overriding an internal resource from a library can be risky since we can't control whether the library will change the usage or naming of that resource.  In other words, it may work now, but it may break when the library is updated.

**Comment by BitsInMyBlood** [comment]
I'm not seeing another angle. If it's going to be fixed NOW, it seems that's the only feasible way to do it, ATM. In the future, hopefully google will rewrite the layout design to provide ways to control the sizing of these items. I less risky solution would be to simplify the text and be content with a one-liner, but you've indicated that solution is not acceptable. I'll keep thinking on it. Maybe there's something I'm missing.
